version: "${API_VERSION}"
services:
  api:
    image: "zcohn93/webapp-gateway-api:${API_VERSION}"
    ports:
      - ${HOST_PORT}:${GUEST_PORT}
    environment:
      - PORT=${GUEST_PORT}
      - DB_URI="${DB_URI}"
      - NETRC="/run/secrets/.netrc"
    secrets:
      - .netrc
      - db_user
      - db_pw

secrets:
  github_token:
    file: secrets/.netrc
  db_user:
    file: secrets/db_user
  db_pw:
    file: secrets/db_pw
